Update syncorg

diff --git a/.local/bin/syncorg b/.local/bin/syncorg
--- a/.local/bin/syncorg
+++ b/.local/bin/syncorg
@@ -2,20 +2,28 @@
 
 CWD="$(pwd)"
 
-if ! [ -d "$1" ] || ! [ -d "$1/.git" ]; then
-  echo "Provide a local git repository" >&2
-  exit 1
-fi
+check_repository() {
+  if ! [ -d "$1" ] || ! [ -d "$1/.git" ]; then
+    echo "Provide a local git repository" >&2
+    exit 1
+  fi
 
-if ! cd "$1"; then
-  echo "Cannot cd in $0" >&2
-  echo "Missing execution permissions ?" >&2
-  exit 1
-fi
+  if ! cd "$1"; then
+    echo "Cannot cd in $0" >&2
+    echo "Missing execution permissions ?" >&2
+    exit 1
+  fi
 
-if ! [ "$(git remote)" ]; then
-  echo "Missing remote server" >&2
-  exit 1
+  if ! [ "$(git remote)" ]; then
+    echo "Missing remote server" >&2
+    cd "$CWD" && exit 1 || exit 1 # just for the LSP
+  fi
+}
+
+if [ "$1" ]; then
+  check_repository "$1"
+else
+  check_repository "$HOME/Notes"
 fi
 
 git pull && $EDITOR . && git add . && git commit -m 'Update' && git push
